### PR TITLE
[WIP] imp.is_frozen() -> __loader__ == importlib.machinery.FrozenImporter

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by altendky** [comment]
I don't know that this is a proper non-deprecated alternative, or even if it works...  but I figured a PR was an easy way to share it and, if the CI test suite is complete, test it.  But I don't know if it is complete.

**Comment by Cheaterman** [comment]
Follow-up on this:
> Frozen modules no longer define a `__file__` attribute. It’s semantically incorrect for frozen modules to set the attribute as they are not loaded from any explicit location. If you must know that a module comes from frozen code then you can see if the module’s `__spec__.location` is set to 'frozen', check if the loader is a subclass of importlib.machinery.FrozenImporter, or if Python 2 compatibility is necessary you can use imp.is_frozen().

Quoted from: https://docs.python.org/3/whatsnew/3.4.html

**Comment by rdb** [comment]
We should use `_imp.is_frozen()`, which is not deprecated, and is actually what is being used by FrozenImporter under the hood.

Panda sets `__file__` (for compatibility with third-party libraries), so that is not a good test.

**Comment by altendky** [comment]
A private (leading `_`) module should presumably not be used directly.  Unless it is publicly documented as a guaranteed interface rather than an implementation detail?

What is the meaning of this module being frozen anyways?  That it is operating in a package it has created?  I don't know this tool at all but I would think that it should be perfectly reasonable to freeze `pman` itself and that that shouldn't inherently affect it's operation.  So I, naively, wonder if there really ought to be a piece of data explicitly set when the transition is made that indicates it should be operating in a different mode.  But yeah, I was just submitting this after trying to help @Cheaterman find something useful.

**Comment by Moguri** [comment]
@altendky Sorry for not getting back to you on this sooner!

pman does some behind-the-scenes stuff to make managing a Panda project a little nicer such as automatically converting assets. However, we don't want this stuff to run in a "release" mode, so we use whether or not the library has been frozen to determine this.

I think `imp.is_frozen()` was used (even though it was deprecated) to maintain Python2 support, which this project dropped a while ago. However, doing some digging, I am not sure why `sys.frozen` isn't being checked instead. I see that Panda *does* set this like other freeze tools (PyInstaller, Cx_Freeze), so it should be safe to use.

**Comment by altendky** [comment]
That sounds like "a piece of data explicitly set when the transition is made that indicates it should be operating in a different mode".  :]  I went and incorrectly updated this but you had already fixed it...  anyways, glad to see a tidy resolution.  Cheers.

**Pull request closed without merging**
